### ISSUE TITLE
ファイルの保存

### ISSUE THREAD

**Issue by ozaki25** [ozaki25/ippo#25]
Lambdaに送ってS3に置く
GraphQLはファイル送信難しいとか見たけどどうなのか

**Comment by aion0721** [comment]
・POSTでアップロードするパターン（HTMLのみでサーバーでの処理不要）
これはアップロードのためにSignatureを用意する必要があり、毎回生成するのか問題等あります。
https://dev.classmethod.jp/cloud/aws-s3-direct-upload/

**Comment by aion0721** [comment]
・Reactで処理するパターン
普通にいけそうです。こちらも署名は作る必要ありそうですが、サーバー側でアクセスキーを持てるのでセキュアかもしれません。
https://qiita.com/akameco/items/277abc7b56cde378f344

**Comment by aion0721** [comment]
React内にS3描きたくないの同意します、、、確かに外で実装したいですね。
Lambdaに投げるってことはAPI Gatewayになるんですかね。なんにせよ相談させてください

**Comment by ozaki25** [comment]
ググってみたらとてもめんどくさそうってことは分かった。。
ブラウザからストレージにファイルをアップロードする、が実現できれば手段は何でもよいかも

**Comment by aion0721** [comment]
ブラウザからストレージへのアップロード機能できました。
http://aion.jp.net/hackson/uploads.html
上記にアクセスしてZipファイルをアップロードしてみてください。問題なければGoogleのページにリダイレクトされます。
https://s3.console.aws.amazon.com/s3/buckets/hackson-test-s3buckets/uploads/?region=ap-northeast-1&tab=overview
そのあと、上記にアクセスしてみるとアップロードされていることがわかります。
（ファイル名わかりづらいですが、0000000.zipになっています。）

使い方は、htmlのソースをほぼパクってくだされば大丈夫です。
ファイル名については、jsでname=keyの部分のhtmlを書き換えてくれれば変更できます。
リダイレクト先を変更するときは少し細工が必要ですので、言ってください。再生成します。

**Comment by aion0721** [comment]
ここまで突貫で作りましたが、イケてないのは重々自覚していますので、
lambdaとか何かでいい感じにここら辺のを生成できないもんかなぁとちょっと試行して見ます。

**Comment by ozaki25** [comment]
アップロードの部分だけ別リポジトリで管理して取り込む予定なのでライブラリの命名お願いします！

**Comment by ozaki25** [comment]
TODO
- key情報を環境変数化
- ファイル名を選択したファイルの名前にする(jsで)

**Comment by ozaki25** [comment]
まずは1,2すっとばして3,4を試して実現性を確認する

**Comment by ozaki25** [comment]
アップロードごファイルのURLをツイート欄に自動で挿入したい
1. アップロード後にstateを更新
1. URLのqueryに情報を付けてURL組み立て
1. storageに入れてなんとかする

**Comment by ozaki25** [comment]
> アップロード後にstateを更新
仕様的にアップロード後に遷移してしまう
> URLのqueryに情報を付けてURL組み立て
有力候補
> storageに入れてなんとかする
最後の手段
