### ISSUE TITLE
メニュー画面を作る

### ISSUE THREAD

**Issue by ozaki25** [ozaki25/ippo#91]
申し込み済みとか公開済みのイベントとか並べる
それぞれ横スワイプできるようにする
https://react-swipeable-views.com

**Comment by aion0721** [comment]
モックにも書いてありますが、イベントとか並べている中に”講師側のメニュー”もかきたい。
最初は、タブで”講師”、”受講”と分けようかと思ったのだが、”講師”のメニューは、自分の講師の一覧が見れれば良いだけなので、特にタブ分けするほどでもないかという形で一緒でいいという話になった。
今は、右下にプラスのボタンがあるが、これは受講生側にとっては混乱するかと思っていますので、
イベントの中の講師のボックスの一つに「新規イベント作成」を作ると良いかも。

**Comment by ozaki25** [comment]
見出しをリンクにして一覧出す
メニューには10件？とかだけ出す

**Comment by ozaki25** [comment]
何件中の何件目かは点で出せる

```js
 <Pagination dots={3} index={index} onChangeIndex={this.handleChangeIndex} />
```
https://react-swipeable-views.com/demos/demos/#auto-play

**Comment by ozaki25** [comment]
イベント作成だけ機能が違うから別タブにしてしまおうかと思ってる
まずはためしに作ってみたい
