### ISSUE TITLE
Reactデプロイ場所

### ISSUE THREAD

**Issue by aion0721** [ozaki25/ippo#95]
今はnetlifyにデプロイされているが、これをS3配置にするとS3で完結するので導入しやすい。
（そもそも、何の理由でnetlify何でしたっけ？DNS周り？）

**Comment by ozaki25** [comment]
Netlifyな理由はゼロコンフィグでauto deployできるから。
それに加えて、ブランチ単位、プルリク単位で自動デプロイできるのも使い勝手がよい(=プルリク単位でurlが生成されてその状態のアプリにいつでもアクセスできる)

**Comment by ozaki25** [comment]
あとはurlにippoって入れられる

**Comment by ozaki25** [comment]
開発中はNetlifyで最後はS3っていうのでもいいと思う

**Comment by aion0721** [comment]
なるほど不勉強で申し訳ないです。
ではこのまま開発中はnetlify使いましょう。
例えば、本番環境へのCDはS3とか運用面を考えたりとかはできそうですね。
